### ISSUE TITLE
Chrome massage: navigator.userAgent replace: Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform

### ISSUE THREAD

**Issue by nagyimre1980** [jquery/jquery-ui#2026]
Chrome 96:

A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.

![Chrome 101](https://user-images.githubusercontent.com/77237828/144381868-9437b175-7404-4bac-96d8-0bc248ecd8f8.JPG)

**Comment by mgol** [comment]
Thanks for the report.

The warnings are caused by the following code: https://github.com/jquery/jquery-ui/blob/1.13.0/ui/ie.js#L17. It was added to detect IE and it's deprecated anyway. The Chrome DevTools warning is harmless; since the code is only used to detect IE, no changes Chrome will make to its User Agent will cause any issues unless they change their UA to look like the one used by old IE - which they won't do as it'd break lots of sites in Chrome.
