### ISSUE TITLE
$.datepicker object undefined after updating to version 1.11.0 and above

### ISSUE THREAD

**Issue by jaa-visma** [jquery/jquery-ui#2027]
We're running jquery-ui version 1.10.0, and all my endeavors to update to any version greater than 1.10.4 results in `$.datepicker` being **undefined**. 

Our import order is
1. jQuery (3.5.0)
2. jQuery-migrate (3.3.2)
3. jQuery-ui

The next file being imported is where we extend the default datepicker functionality in this manner:
```js
; (function () {
        var oldMethod = $.datepicker._doKeyDown;
        var oldGenerate = $.datepicker._generateHTML;

        $.extend($.datepicker, {
		_doKeyDown: function (event) { ... },
		_generateHTML: function () { ... },
                _gotoToday : function(id) { ... }
        });
})(window.$);
```

This throws an error on the first line, when trying to access the `_doKeyDown` on the **undefined** `$.datepicker` object. We use `$.datepicker` extensively throughout our codebase.

I see from the [changelogs to jQuery-1.11](https://jqueryui.com/changelog/1.11.0/) that the way widgets are wrapped has changed, is there a relation to my problem?

> Added: AMD support via UMD wrappers. ([96e027e](https://github.com/jquery/jquery-ui/commit/96e027e4b14345722cc39589f59ce2ce5e94b991), [1216e2a](https://github.com/jquery/jquery-ui/commit/1216e2aaf5e9bae52abe1ef9dfb9ab34c271c56d))

**Comment by mgol** [comment]
I'm not sure how you load jQuery UI but in the generated file `$.datepicker` is generally available. I'd suggest looking for help with this on Stack Overflow as there's likely an issue on your end. If it turns out otherwise and you have a concrete test case, we can reopen.

That said, issues in versions older than 1.13 are not really looked at; see the project status at https://blog.jqueryui.com/2021/10/jquery-maintainers-update-and-transition-jquery-ui-as-part-of-overall-modernization-efforts/.
