### ISSUE TITLE
Fix broken Github Jenkins integration

### ISSUE THREAD

**Issue by fnagel** [jquery/jquery-ui#2028]
Github webhook with Jenkins doesn't work.

**Comment by mgol** [comment]
We're getting rid of Jenkins so this is no longer important. For now, UI tests are running weekly against all supported Core releases so we are covered.

However, I added a workaround by turning on the Poll SCM option in Jenkins in the "jQuery UI - git core" job. That option has been enabled for Core jobs as well until they recently got disabled (when all the responsibilities of these jobs were migrated to GitHub Actions). Hopefully that's enough in this transitional period.

I removed the webhook from settings since it doesn't work anyway.

**Comment by fnagel** [comment]
Thanks for the info @mgol!
