### ISSUE TITLE
jquery-ui.structure.min.css missing from npm package

### ISSUE THREAD

**Issue by enviroQL** [jquery/jquery-ui#2172]
`jquery-ui.structure.min.css` is avaiable from the download package but missing from npm install. how can I use `jquery-ui.structure.min.css` from npm install? thx!

**Comment by mgol** [comment]
Thanks for the report.

We don't even share these files on the jQuery CDN, the only seem to exist in the zip files.

We only added the full CSS file to the npm package for cdnjs which would otherwise not be able to share the newest jQuery UI versions (#2011).

Since the issue is already in 1.12, given limited team resources it's not likely to be fixed by the UI team; see the project status at https://blog.jqueryui.com/2021/10/jquery-maintainers-update-and-transition-jquery-ui-as-part-of-overall-modernization-efforts/.

**Comment by enviroQL** [comment]
thanks for the reply. issue closed.
