### ISSUE TITLE
Publishing older versions to NPM request

### ISSUE THREAD

**Issue by flipatlas** [jquery/jquery-ui#2214]
Hey,

Would it be possible to publish the older versions (jquery-ui@1.8) to the NPM registry?

There’s probably more reasons others would like it on the registry, for us, we would be able to correctly attribute the project with the right credit and provide the right license information.

Thanks

**Comment by mgol** [comment]
Considering that jQuery UI is in maintenance mode, I don't think we want to change anything about obsolete UI versions. Note that even jQuery Core doesn't have versions older than 1.11/2.1 on npm. Unfortunately, I have to decline this request.

**Comment by Ascor8522** [comment]
Hello 👋 

Would it be possible to do it for versions jQuery Core **that are available** on npm but missing for jQuery UI?
I'm mainly referring to **jQuery UI 1.11.4**, which is used in a project in inherited.

jQuery (Core) 1.12.3 is available on npm, but jQuery UI 1.11.4 isn't.


It is especially weird since the versions 1.10.4 and 1.10.5 are available, but all of the 1.11.x aren't.

Kinda annoying that jQuery UI is **one of our only dependencies not available on npm**. This involves keeping a separate copy in our repo (added to version control) and needing a custom module resolution setup.

This wouldn't be a problem if the different CDNs (and the jQuery UI website) were offering a link to a tarball containing the whole library, instead of links to each file separately, but this is not the case.


Adding the missing versions would be greatly appreciated 👍

**Comment by mgol** [comment]
Zips for releases are available at https://jqueryui.com/download/all/. This page is linked from https://jqueryui.com/download/.

**Comment by Ascor8522** [comment]
Thank you for the quick response @mgol, however, the zip files you are referring to are now what I need.

In my previous message, I explicitly mentioned **tarballs**, implying those would be used to install the library using npm, since it is [a source npm supports installing from](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#urls-as-dependencies). Those archives should thus contain a `package.json` file, as well as have the folder structure usually found in regular npm packages. Basically an npm package, but as a single tarball.

Also noticed the GitHub repo has some [releases](https://github.com/jquery/jquery-ui/releases) available, but the build artifacts are not made available and also only go back to version 1.13.


I was hoping the jQuery UI team could use those zip files you mentioned and re-package them as npm packages (with a `package.json` and the right folder structure) and upload them on the npm registry. And this for at least the 1.11.4 version, since it's the last one for the 1.11 series.

Again, this would help a lot.

**Comment by mgol** [comment]
Touching older releases carries some risk, especially that the process to build & release jQuery UI is quite complex and we’d have to restore a number of repositories to older versions and who knows what else.

Also, we barely have resources for maintaining the current version of jQuery UI; adding more work for old & long unsupported releases is definitely not something I want to do.

On the other hand, if the goal is to just have some built jQuery UI files in an npm package, you can publish such a package by yourself under a custom name using files from the zip archives. Thanks to npm supporting package aliases, you can still have it available under `jquery-ui` in your project.

**Comment by GedMarc** [comment]
There has to be a line drawn where the owners of repositories can just say, No. Backwards compatibility management is at the fault of the user, it isn't a reason to not move forward
