### ISSUE TITLE
Autocomplete as a combobox does no more show the dropdown button

### ISSUE THREAD

**Issue by fredericDelaporte** [jquery/jquery-ui#2295]
The autocomplete widget as a combobox does no more show its dropdown button.

That is visible in the documentation examples, [here](https://jqueryui.com/autocomplete/#combobox).

**Comment by mgol** [comment]
Thanks for the report. Does the issue you describe exist when jQuery UI 1.12.1 is used or only with jQuery UI 1.13.0 or newer?

**Comment by fredericDelaporte** [comment]
No idea about when this trouble has appeared on the jQuery UI documentation site.

On a private application I am working on, the trouble is not there on the commit preceding an upgrade from v1.13.3 to v1.14.0, and is there on that commit.

**Comment by mgol** [comment]
Thanks for the info! I narrowed it down to be caused by disabling back compat (i.e. setting `$.uiBackCompat` to `false` in jQuery UI 1.13 or older or by NOT setting it to `true` in jQuery UI 1.14). What's left is to understand why this flag matters here and if there's some logic we should move to not be dependent on this flag.

**Comment by mgol** [comment]
Fortunately, this was just an issue with the demo which used deprecated `button` options: [`icons`](https://jqueryui.com/upgrade-guide/1.12/#deprecated-icons-options-in-favor-of-icon-and-iconposition) and [`text`](https://jqueryui.com/upgrade-guide/1.12/#deprecated-text-option-in-favor-of-showlabel).

I fixed the demos in PR #2296.

**Comment by mgol** [comment]
The demo works correctly now.
