### ISSUE TITLE
[UI Position 1.14.1] Uncaught SyntaxError: Missing initializer in using

### ISSUE THREAD

**Issue by alex-solovyev** [jquery/jquery-ui#2314]
I started encountering an error after upgrading Google Chrome to Version 131.0.6778.86 (Official Build) (x86_64).

The issue is reproducible only when using the uncompressed version of jQuery UI.
The relevant code:

```javascript
if (options.using) {
    // Adds feedback as the second argument to the using callback, if present
    using = function(props) {
      // skipped...
    };
}
```
It seems that the variable using is being used as a function without being declared properly. Adding `var` in front of `using` resolves the issue.

Example: [CodePen link](https://codepen.io/alex-solovyev/full/ZEggZgX)

**Comment by alex-solovyev** [comment]
That's odd, but I cannot reproduce the issue when using Google Chrome for Testing on the same laptop (macOS Monterey 12.7.6, Intel processor).
<img width="1042" alt="Screenshot 2024-11-25 at 13 50 40" src="https://github.com/user-attachments/assets/153b6aea-637c-4bad-a04e-2bebacbc7250">

The issue only appears in the version of the browser installed from https://dl.google.com/chrome/mac/universal/stable/GGRO/googlechrome.dmg
<img width="1023" alt="Screenshot 2024-11-25 at 14 08 19" src="https://github.com/user-attachments/assets/f29bf465-03d8-4996-aff8-c0b09031b565">

**Comment by dmethvin** [comment]
There's a proposed new TC39 feature that creates a `using` keyword. 
https://github.com/tc39/proposal-explicit-resource-management

Based on the error message, it seems like the attempt to parse that line as a `using` statement is the cause. However, the current code is valid Javascript. That `using` variable is declared earlier in the scope. 

<img width="496" alt="image" src="https://github.com/user-attachments/assets/facd0956-f8af-474c-9a6a-0367453dcaa1">

I would report this problem to Chrome as a bug. Changing this line in jQuery UI will not really help, because there are so many sites using the current jQuery UI version that will not be updated. All of those sites would still be broken.

**Comment by alex-solovyev** [comment]
Thank you, @dmethvin! I missed that it was declared above in the code.

Related issues:

- [tc39/proposal-explicit-resource-management#247](https://github.com/tc39/proposal-explicit-resource-management/issues/247)

- [Chromium Issue #379888466](https://issues.chromium.org/issues/379888466)
